[project]
name = "simlify"
authors = [
    "OASCI <us@oasci.org>",
]
channels = ["conda-forge"]
description = "Simplify your molecular simulation workflow."
platforms = ["linux-64", "osx-64", "osx-arm64"]
license = "Apache-2.0"
readme = "README.md"

[pypi-dependencies]
simlify = { path = ".", editable = true }
pyyaml = ">=6.0.2, <7"

[environments]
dev = ["dev"]
docs = ["docs"]

[tasks]

[dependencies]
python = ">=3.10"
numpy = ">=1.2.6,<3"
scipy = ">=1.15.2,<2"
pydantic = ">=2.10.6,<3"
mdanalysis = ">=2.9.0,<3"

[feature.dev.dependencies]
isort = ">=5.12.0"
pylint = ">=3.0.1"
mypy = ">=1.6.0"
pytest = ">=7.4.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.3.1"
pytest-html = ">=4.0.1"
colorama = ">=0.4.6"
ambertools = ">=24.8,<25"
basedpyright = ">=1.29.1,<2"
ruff = ">=0.11.8,<1"
twine = ">=6.1.0,<7"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"docs/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./simlify", "./tests", "||", "true"] }
ruff = { cmd = ["ruff", "format", "--config", ".ruff.toml", "./simlify", "./tests", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "ruff"] }
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='simlify'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"
mypy-extensions = ">=1.0.0"
pyrefly = ">=0.16.0, <1"
setuptools-scm = ">=8.0.0"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.5,<10"
mkdocstrings = ">=0.28.2,<1"
mkdocstrings-python = ">=1.16.2,<2"
pymdown-extensions = ">=10.14.3,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocs-gen-files = ">=0.4.0,<1"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-jupyter = ">=0.25.1,<1"
mkdocs-glightbox = ">=0.4.0,<1"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0,<1"
mkdocs-print-site-plugin = ">=2.6.0,<3"
mkdocs-awesome-nav = ">=3.0.0,<4"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"] }
serve = { cmd = ["mkdocs", "serve"] }
